const data = [
  {
    delivery_time: "Express 24H",
    budget: 5000,
    language: "hindi",
    category: "Adobe Photoshop",
    subcategory: "Photo Editing",
    level: "Basic level",
    rating: 4.5,
    review: 28,
    courseName: "Photo Editing Fundamentals",
    date: "2024-01-01",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 3000,
    language: "english",
    category: "Figma",
    subcategory: "UI Design",
    level: "Standard level",
    rating: 4.2,
    review: 35,
    courseName: "UI Design Essentials",
    date: "2022-01-02",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 7000,
    language: "urdu",
    category: "Sketch",
    subcategory: "Wireframing",
    level: "Beginner level",
    rating: 4.7,
    review: 19,
    courseName: "Wireframing Basics",
    date: "2023-01-03",
  },
  {
    delivery_time: "Anytime",
    budget: 8000,
    language: "japanese",
    category: "Adobe XD",
    subcategory: "Prototyping",
    level: "Advanced level",
    rating: 4.9,
    review: 42,
    courseName: "Advanced Prototyping Techniques",
    date: "2022-01-04",
  },
  {
    delivery_time: "Express 24H",
    budget: 4500,
    language: "spanish",
    category: "WebDesign",
    subcategory: "Responsive Design",
    level: "Standard level",
    rating: 4.3,
    review: 31,
    courseName: "Responsive Web Design Mastery",
    date: "2022-01-05",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 5500,
    language: "french",
    category: "Adobe Photoshop",
    subcategory: "Graphic Design",
    level: "Advanced level",
    rating: 4.6,
    review: 25,
    courseName: "Mastering Graphic Design Principles",
    date: "2022-01-06",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 4000,
    language: "german",
    category: "Figma",
    subcategory: "Wireframing",
    level: "Standard level",
    rating: 4.1,
    review: 37,
    courseName: "Figma Wireframing Techniques",
    date: "2022-01-07",
  },
  {
    delivery_time: "Anytime",
    budget: 7500,
    language: "italian",
    category: "Sketch",
    subcategory: "UI Design",
    level: "Beginner level",
    rating: 4.4,
    review: 29,
    courseName: "Intro to Sketch UI Design",
    date: "2022-01-08",
  },
  {
    delivery_time: "Express 24H",
    budget: 6000,
    language: "punjabi",
    category: "Adobe XD",
    subcategory: "Prototyping",
    level: "Basic level",
    rating: 4.8,
    review: 23,
    courseName: "Fundamentals of XD Prototyping",
    date: "2022-01-09",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 3500,
    language: "english",
    category: "WebDesign",
    subcategory: "Responsive Design",
    level: "Beginner level",
    rating: 4.2,
    review: 32,
    courseName: "Responsive Web Design for Beginners",
    date: "2022-01-10",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 6500,
    language: "urdu",
    category: "Figma",
    subcategory: "UI Design",
    level: "Advanced level",
    rating: 4.7,
    review: 27,
    courseName: "Advanced UI Design Strategies",
    date: "2022-01-11",
  },
  {
    delivery_time: "Anytime",
    budget: 4200,
    language: "arabic",
    category: "Sketch",
    subcategory: "Wireframing",
    level: "Standard level",
    rating: 4.3,
    review: 36,
    courseName: "Sketch Wireframing Fundamentals",
    date: "2022-01-12",
  },
  {
    delivery_time: "Express 24H",
    budget: 4800,
    language: "hindi",
    category: "Adobe Photoshop",
    subcategory: "Graphic Design",
    level: "Basic level",
    rating: 4.6,
    review: 24,
    courseName: "Introduction to Graphic Design",
    date: "2022-01-13",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 5200,
    language: "punjabi",
    category: "Adobe XD",
    subcategory: "Prototyping",
    level: "Standard level",
    rating: 4.5,
    review: 26,
    courseName: "Adobe XD Prototyping Workshop",
    date: "2022-01-14",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 6800,
    language: "urdu",
    category: "Figma",
    subcategory: "Wireframing",
    level: "Advanced level",
    rating: 4.8,
    review: 22,
    courseName: "Mastering Figma Wireframing",
    date: "2022-01-15",
  },
  {
    delivery_time: "Anytime",
    budget: 7800,
    language: "punjabi",
    category: "Sketch",
    subcategory: "UI Design",
    level: "Beginner level",
    rating: 4.4,
    review: 30,
    courseName: "UI Design Fundamentals",
    date: "2022-01-16",
  },
  {
    delivery_time: "Express 24H",
    budget: 6200,
    language: "urdu",
    category: "WebDesign",
    subcategory: "Responsive Design",
    level: "Basic level",
    rating: 4.2,
    review: 33,
    courseName: "Responsive Web Design Basics",
    date: "2022-01-17",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 3700,
    language: "punjabi",
    category: "Adobe Photoshop",
    subcategory: "Photo Editing",
    level: "Standard level",
    rating: 4.7,
    review: 21,
    courseName: "Advanced Photo Editing Techniques",
    date: "2022-01-18",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 4200,
    language: "english",
    category: "Figma",
    subcategory: "UI Design",
    level: "Beginner level",
    rating: 4.3,
    review: 34,
    courseName: "Figma UI Design Fundamentals",
    date: "2022-01-19",
  },
  {
    delivery_time: "Anytime",
    budget: 7900,
    language: "hindi",
    category: "Sketch",
    subcategory: "Wireframing",
    level: "Advanced level",
    rating: 4.9,
    review: 20,
    courseName: "Advanced Sketch Wireframing",
    date: "2022-01-20",
  },
  {
    delivery_time: "Express 24H",
    budget: 5400,
    language: "punjabi",
    category: "Adobe XD",
    subcategory: "Prototyping",
    level: "Basic level",
    rating: 4.5,
    review: 29,
    courseName: "Intro to Adobe XD Prototyping",
    date: "2022-01-21",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 4900,
    language: "english",
    category: "WebDesign",
    subcategory: "Responsive Design",
    level: "Standard level",
    rating: 4.2,
    review: 31,
    courseName: "Web Design Principles",
    date: "2022-01-22",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 7300,
    language: "urdu",
    category: "Figma",
    subcategory: "Wireframing",
    level: "Advanced level",
    rating: 4.8,
    review: 25,
    courseName: "Advanced Figma Wireframing",
    date: "2022-01-23",
  },
  {
    delivery_time: "Anytime",
    budget: 7700,
    language: "spanish",
    category: "Adobe XD",
    subcategory: "Prototyping",
    level: "Advanced level",
    rating: 4.7,
    review: 27,
    courseName: "Advanced Adobe XD Prototyping",
    date: "2022-01-24",
  },
  // Add 23 more objects with different values here
  {
    delivery_time: "Express 24H",
    budget: 5700,
    language: "hindi",
    category: "Adobe Photoshop",
    subcategory: "Graphic Design",
    level: "Beginner level",
    rating: 4.3,
    review: 23,
    courseName: "Graphic Design Basics",
    date: "2022-01-25",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 6800,
    language: "urdu",
    category: "Figma",
    subcategory: "UI Design",
    level: "Advanced level",
    rating: 4.6,
    review: 26,
    courseName: "Advanced Figma UI Design",
    date: "2022-01-26",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 4900,
    language: "punjabi",
    category: "Sketch",
    subcategory: "Wireframing",
    level: "Standard level",
    rating: 4.1,
    review: 29,
    courseName: "Sketch Wireframing Essentials",
    date: "2022-01-27",
  },
  {
    delivery_time: "Anytime",
    budget: 7200,
    language: "english",
    category: "Adobe XD",
    subcategory: "Prototyping",
    level: "Basic level",
    rating: 4.4,
    review: 31,
    courseName: "Adobe XD Prototyping Basics",
    date: "2022-01-28",
  },
  {
    delivery_time: "Express 24H",
    budget: 6300,
    language: "hindi",
    category: "WebDesign",
    subcategory: "Responsive Design",
    level: "Standard level",
    rating: 4.7,
    review: 28,
    courseName: "Responsive Web Design Advanced",
    date: "2022-01-29",
  },
  {
    delivery_time: "Up to 3 days",
    budget: 3900,
    language: "punjabi",
    category: "Adobe Photoshop",
    subcategory: "Photo Editing",
    level: "Beginner level",
    rating: 4.2,
    review: 35,
    courseName: "Photo Editing Essentials",
    date: "2022-01-30",
  },
  {
    delivery_time: "Up to 7 days",
    budget: 4600,
    language: "english",
    category: "Figma",
    subcategory: "UI Design",
    level: "Standard level",
    rating: 4.5,
    review: 30,
    courseName: "Figma UI Design Mastery",
    date: "2022-01-31",
  },
];

export default data;
